name: Test
on: push
jobs:
  lint:
    runs-: ubuntu-latest # на чем запускается
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint





