name: Test



on:
  pull_request:  # Запускать при создании pull request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          pytest tests

      - name: Run mypy
        run: |
          mypy src/

      - name: Run black
        run: |
          black --diff --check src/

      - name: Run isort
        run: |
          isort --check-only --diff src/

      - name: Run flake8
        run: |
          flake8 src/


